name: Draft Deployment

on:
  workflow_dispatch:

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy on Web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run deploy:web -- --repo=https://${{secrets.GH_TOKEN}}@github.com/CATcher-staging/CATcher.git